plugins {
    id 'com.android.application'
}

android {
    namespace 'com.recgombak.batterymonitor'
    compileSdk 35

    defaultConfig {
        applicationId 'com.recgombak.batterymonitor.v2'
        minSdk 23
        targetSdk 35
        versionCode 24
        versionName '2.4'
    }

    signingConfigs {
        stableDebug {
            storeFile file('../signing/rec-monitor-debug.keystore')
            storePassword 'recmonitor123'
            keyAlias 'recmonitor'
            keyPassword 'recmonitor123'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.stableDebug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
