package com.recgombak.batterymonitor;

import android.app.*; import android.content.*; import android.net.DhcpInfo; import android.net.wifi.WifiManager; import android.os.*; import org.json.JSONObject; import java.net.*; import java.nio.charset.StandardCharsets;

public class BatteryBroadcastService extends Service {
 public static final int PORT=45888; private static final String CHANNEL_ID="rec_battery_status"; private volatile boolean running=false; private Thread worker;
 @Override public void onCreate(){ super.onCreate(); createChannel(); startForeground(1001,buildNotification(getBatteryPercent(),isCharging())); }
 @Override public int onStartCommand(Intent intent,int flags,int startId){ if(!Prefs.isEnabled(this)){stopSelf();return START_NOT_STICKY;} if(!running){running=true;worker=new Thread(this::loop,"REC-Battery-Broadcast");worker.start();} return START_STICKY; }
 private void loop(){ while(running){ try{ int battery=getBatteryPercent(); boolean charging=isCharging(); JSONObject obj=new JSONObject(); obj.put("app","REC_BATTERY_V1");obj.put("id",Prefs.getId(this));obj.put("name",Prefs.getName(this));obj.put("model",Build.MANUFACTURER+" "+Build.MODEL);obj.put("battery",battery);obj.put("charging",charging);obj.put("ts",System.currentTimeMillis()); byte[] data=obj.toString().getBytes(StandardCharsets.UTF_8); sendPacket(data,"255.255.255.255"); String subnet=getSubnetBroadcast(); if(subnet!=null&&!"255.255.255.255".equals(subnet))sendPacket(data,subnet); updateNotification(battery,charging); }catch(Exception ignored){} try{Thread.sleep(15000);}catch(InterruptedException e){Thread.currentThread().interrupt();break;} } }
 private void sendPacket(byte[] data,String address){ try(DatagramSocket socket=new DatagramSocket()){socket.setBroadcast(true);DatagramPacket packet=new DatagramPacket(data,data.length,InetAddress.getByName(address),PORT);socket.send(packet);}catch(Exception ignored){} }
 @SuppressWarnings("deprecation") private String getSubnetBroadcast(){ try{WifiManager wifi=(WifiManager)getApplicationContext().getSystemService(Context.WIFI_SERVICE);DhcpInfo dhcp=wifi.getDhcpInfo();if(dhcp==null)return null;int broadcast=(dhcp.ipAddress&dhcp.netmask)|~dhcp.netmask;byte[] q=new byte[4];for(int k=0;k<4;k++)q[k]=(byte)((broadcast>>k*8)&0xFF);return InetAddress.getByAddress(q).getHostAddress();}catch(Exception e){return null;} }
 private Intent batteryIntent(){return registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));}
 private int getBatteryPercent(){Intent i=batteryIntent();if(i==null)return -1;int level=i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),scale=i.getIntExtra(BatteryManager.EXTRA_SCALE,100);return scale>0?Math.round(level*100f/scale):level;}
 private boolean isCharging(){Intent i=batteryIntent();if(i==null)return false;int s=i.getIntExtra(BatteryManager.EXTRA_STATUS,-1);return s==BatteryManager.BATTERY_STATUS_CHARGING||s==BatteryManager.BATTERY_STATUS_FULL;}
 private void createChannel(){if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){NotificationChannel ch=new NotificationChannel(CHANNEL_ID,"REC Battery Monitor",NotificationManager.IMPORTANCE_LOW);ch.setDescription("Status bateri melalui Wi-Fi tempatan");getSystemService(NotificationManager.class).createNotificationChannel(ch);}}
 private Notification buildNotification(int battery,boolean charging){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);String text=(battery>=0?battery+"%":"-")+(charging?" • sedang dicas":" • aktif di WLAN");Notification.Builder b=Build.VERSION.SDK_INT>=Build.VERSION_CODES.O?new Notification.Builder(this,CHANNEL_ID):new Notification.Builder(this);return b.setContentTitle("REC Battery Monitor").setContentText(text).setSmallIcon(android.R.drawable.ic_lock_idle_charging).setContentIntent(pi).setOngoing(true).build();}
 private void updateNotification(int b,boolean c){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1001,buildNotification(b,c));}
 @Override public void onDestroy(){running=false;if(worker!=null)worker.interrupt();super.onDestroy();} @Override public IBinder onBind(Intent intent){return null;}
}
