package com.recgombak.batterymonitor;

import android.app.*;import android.content.*;import android.media.*;import android.net.DhcpInfo;import android.net.wifi.WifiManager;import android.os.*;import org.json.JSONObject;import java.net.*;import java.nio.charset.StandardCharsets;

public class BatteryBroadcastService extends Service{
 public static final int PORT=45888;private static final String CHANNEL_ID="rec_battery_status",TIMER_CHANNEL="rec_timer_alarm_v3";private volatile boolean running=false;private Thread worker,commandWorker;private long lastTimerEnd=0;
 @Override public void onCreate(){super.onCreate();createChannels();startForeground(1001,buildNotification(getBatteryPercent(),isCharging()));}
 @Override public int onStartCommand(Intent i,int f,int id){if(!Prefs.isEnabled(this)){stopSelf();return START_NOT_STICKY;}if(!running){running=true;worker=new Thread(this::loop,"REC-Battery-Broadcast");worker.start();commandWorker=new Thread(this::listenCommands,"REC-Commands");commandWorker.start();}return START_STICKY;}
 private void loop(){while(running){try{checkTimer();if(Prefs.inSchedule(this))sendStatus();updateNotification(getBatteryPercent(),isCharging());}catch(Exception ignored){}try{Thread.sleep(Math.min(5000L,Prefs.inSchedule(this)?Prefs.getInterval(this)*1000L:5000L));}catch(InterruptedException e){break;}}}
 private void checkTimer(){long end=Prefs.getTimerEnd(this);if(end!=lastTimerEnd){lastTimerEnd=end;if(end>System.currentTimeMillis())Prefs.setTimerAlarmed(this,false);}if(end>0&&System.currentTimeMillis()>=end&&!Prefs.isTimerAlarmed(this)){Prefs.setTimerAlarmed(this,true);playTimerAlarm();showTimerNotification();openTimeUpScreen();sendStatus();}}
 private void openTimeUpScreen(){try{Intent i=new Intent(this,TimeUpActivity.class);i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);startActivity(i);}catch(Exception ignored){}}
 private void playTimerAlarm(){new Thread(()->{ToneGenerator tg=null;try{AudioManager am=(AudioManager)getSystemService(AUDIO_SERVICE);am.setStreamVolume(AudioManager.STREAM_ALARM,am.getStreamMaxVolume(AudioManager.STREAM_ALARM),0);tg=new ToneGenerator(AudioManager.STREAM_ALARM,100);long until=System.currentTimeMillis()+7000;while(System.currentTimeMillis()<until){tg.startTone(ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD,900);Thread.sleep(1000);}}catch(Exception ignored){}finally{if(tg!=null)tg.release();}}).start();}
 private void showTimerNotification(){Intent open=new Intent(this,TimeUpActivity.class);open.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent pi=PendingIntent.getActivity(this,77,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,TIMER_CHANNEL):new Notification.Builder(this);Notification n=b.setContentTitle("MASA TAMAT").setContentText(Prefs.getName(this)+" — masa penggunaan telah tamat").setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentIntent(pi).setFullScreenIntent(pi,true).setAutoCancel(false).setPriority(Notification.PRIORITY_MAX).setCategory(Notification.CATEGORY_ALARM).build();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(2002,n);}
 private void sendStatus(){try{int b=getBatteryPercent();boolean c=isCharging();JSONObject o=new JSONObject();o.put("app","REC_BATTERY_V3");o.put("type","status");o.put("id",Prefs.getId(this));o.put("name",Prefs.getName(this));o.put("model",Build.MANUFACTURER+" "+Build.MODEL);o.put("battery",b);o.put("charging",c);o.put("timerEnd",Prefs.getTimerEnd(this));o.put("ts",System.currentTimeMillis());send(o);}catch(Exception ignored){}}
 private void listenCommands(){try(DatagramSocket s=new DatagramSocket(null)){s.setReuseAddress(true);s.setBroadcast(true);s.bind(new InetSocketAddress(PORT+1));s.setSoTimeout(3000);byte[] buf=new byte[2048];while(running){try{DatagramPacket p=new DatagramPacket(buf,buf.length);s.receive(p);JSONObject o=new JSONObject(new String(p.getData(),p.getOffset(),p.getLength(),StandardCharsets.UTF_8));String app=o.optString("app");if(!"REC_BATTERY_V3".equals(app)&&!"REC_BATTERY_V2".equals(app))continue;String target=o.optString("target","ALL");if(!"ALL".equals(target)&&!Prefs.getId(this).equals(target))continue;String cmd=o.optString("cmd");if("refresh".equals(cmd))sendStatus();else if("timer".equals(cmd)){Prefs.setTimerEnd(this,System.currentTimeMillis()+Math.max(0,o.optInt("minutes",0))*60000L);Prefs.setTimerAlarmed(this,false);sendStatus();}else if("clearTimer".equals(cmd)){Prefs.setTimerEnd(this,0);Prefs.setTimerAlarmed(this,false);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).cancel(2002);sendStatus();}}catch(SocketTimeoutException ignored){}catch(Exception ignored){}}}catch(Exception ignored){}}
 private void send(JSONObject o){try{byte[] d=o.toString().getBytes(StandardCharsets.UTF_8);sendPacket(d,"255.255.255.255");String sub=getSubnetBroadcast();if(sub!=null&&!"255.255.255.255".equals(sub))sendPacket(d,sub);}catch(Exception ignored){}}
 private void sendPacket(byte[] d,String a){try(DatagramSocket s=new DatagramSocket()){s.setBroadcast(true);s.send(new DatagramPacket(d,d.length,InetAddress.getByName(a),PORT));}catch(Exception ignored){}}
 @SuppressWarnings("deprecation")private String getSubnetBroadcast(){try{WifiManager w=(WifiManager)getApplicationContext().getSystemService(Context.WIFI_SERVICE);DhcpInfo d=w.getDhcpInfo();if(d==null)return null;int b=(d.ipAddress&d.netmask)|~d.netmask;byte[] q=new byte[4];for(int k=0;k<4;k++)q[k]=(byte)((b>>k*8)&255);return InetAddress.getByAddress(q).getHostAddress();}catch(Exception e){return null;}}
 private Intent batteryIntent(){return registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));}private int getBatteryPercent(){Intent i=batteryIntent();if(i==null)return-1;int l=i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),s=i.getIntExtra(BatteryManager.EXTRA_SCALE,100);return s>0?Math.round(l*100f/s):l;}private boolean isCharging(){Intent i=batteryIntent();if(i==null)return false;int s=i.getIntExtra(BatteryManager.EXTRA_STATUS,-1);return s==BatteryManager.BATTERY_STATUS_CHARGING||s==BatteryManager.BATTERY_STATUS_FULL;}
 private void createChannels(){if(Build.VERSION.SDK_INT>=26){NotificationManager nm=getSystemService(NotificationManager.class);NotificationChannel c=new NotificationChannel(CHANNEL_ID,"REC Battery Monitor",NotificationManager.IMPORTANCE_LOW);nm.createNotificationChannel(c);NotificationChannel t=new NotificationChannel(TIMER_CHANNEL,"Timer Tamat",NotificationManager.IMPORTANCE_HIGH);t.setDescription("Penggera dan skrin penuh apabila timer tablet tamat");t.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);nm.createNotificationChannel(t);}}
 private Notification buildNotification(int b,boolean c){PendingIntent pi=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);String txt=Prefs.inSchedule(this)?((b>=0?b+"%":"-")+(c?" • sedang dicas":" • pemantauan aktif")):"Di luar waktu pemantauan";Notification.Builder n=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL_ID):new Notification.Builder(this);return n.setContentTitle("REC Battery Monitor").setContentText(txt).setSmallIcon(android.R.drawable.ic_lock_idle_charging).setContentIntent(pi).setOngoing(true).build();}private void updateNotification(int b,boolean c){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1001,buildNotification(b,c));}
 @Override public void onDestroy(){running=false;if(worker!=null)worker.interrupt();if(commandWorker!=null)commandWorker.interrupt();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
