package com.recgombak.batterymonitor;

import android.app.*; import android.content.*; import android.net.DhcpInfo; import android.net.wifi.WifiManager; import android.os.*; import org.json.JSONObject; import java.net.*; import java.nio.charset.StandardCharsets;

public class BatteryBroadcastService extends Service {
 public static final int PORT=45888; private static final String CHANNEL_ID="rec_battery_status"; private volatile boolean running=false; private Thread worker,commandWorker;
 @Override public void onCreate(){super.onCreate();createChannel();startForeground(1001,buildNotification(getBatteryPercent(),isCharging()));}
 @Override public int onStartCommand(Intent i,int f,int id){if(!Prefs.isEnabled(this)){stopSelf();return START_NOT_STICKY;}if(!running){running=true;worker=new Thread(this::loop,"REC-Battery-Broadcast");worker.start();commandWorker=new Thread(this::listenCommands,"REC-Commands");commandWorker.start();}return START_STICKY;}
 private void loop(){while(running){try{if(Prefs.inSchedule(this))sendStatus();updateNotification(getBatteryPercent(),isCharging());}catch(Exception ignored){}try{Thread.sleep(Prefs.inSchedule(this)?Prefs.getInterval(this)*1000L:60000L);}catch(InterruptedException e){break;}}}
 private void sendStatus(){try{int b=getBatteryPercent();boolean c=isCharging();JSONObject o=new JSONObject();o.put("app","REC_BATTERY_V2");o.put("type","status");o.put("id",Prefs.getId(this));o.put("name",Prefs.getName(this));o.put("model",Build.MANUFACTURER+" "+Build.MODEL);o.put("battery",b);o.put("charging",c);o.put("timerEnd",Prefs.getTimerEnd(this));o.put("ts",System.currentTimeMillis());send(o);}catch(Exception ignored){}}
 private void listenCommands(){try(DatagramSocket s=new DatagramSocket(null)){s.setReuseAddress(true);s.setBroadcast(true);s.bind(new InetSocketAddress(PORT+1));s.setSoTimeout(3000);byte[] buf=new byte[2048];while(running){try{DatagramPacket p=new DatagramPacket(buf,buf.length);s.receive(p);JSONObject o=new JSONObject(new String(p.getData(),p.getOffset(),p.getLength(),StandardCharsets.UTF_8));if(!"REC_BATTERY_V2".equals(o.optString("app")))continue;String target=o.optString("target","ALL");if(!"ALL".equals(target)&&!Prefs.getId(this).equals(target))continue;String cmd=o.optString("cmd");if("refresh".equals(cmd))sendStatus();else if("timer".equals(cmd)){Prefs.setTimerEnd(this,System.currentTimeMillis()+Math.max(0,o.optInt("minutes",0))*60000L);sendStatus();}else if("clearTimer".equals(cmd)){Prefs.setTimerEnd(this,0);sendStatus();}}catch(SocketTimeoutException ignored){}catch(Exception ignored){}}}catch(Exception ignored){}}
 private void send(JSONObject o){try{byte[] d=o.toString().getBytes(StandardCharsets.UTF_8);sendPacket(d,"255.255.255.255");String sub=getSubnetBroadcast();if(sub!=null&&!"255.255.255.255".equals(sub))sendPacket(d,sub);}catch(Exception ignored){}}
 private void sendPacket(byte[] d,String a){try(DatagramSocket s=new DatagramSocket()){s.setBroadcast(true);s.send(new DatagramPacket(d,d.length,InetAddress.getByName(a),PORT));}catch(Exception ignored){}}
 @SuppressWarnings("deprecation") private String getSubnetBroadcast(){try{WifiManager w=(WifiManager)getApplicationContext().getSystemService(Context.WIFI_SERVICE);DhcpInfo d=w.getDhcpInfo();if(d==null)return null;int b=(d.ipAddress&d.netmask)|~d.netmask;byte[] q=new byte[4];for(int k=0;k<4;k++)q[k]=(byte)((b>>k*8)&255);return InetAddress.getByAddress(q).getHostAddress();}catch(Exception e){return null;}}
 private Intent batteryIntent(){return registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));} private int getBatteryPercent(){Intent i=batteryIntent();if(i==null)return-1;int l=i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),s=i.getIntExtra(BatteryManager.EXTRA_SCALE,100);return s>0?Math.round(l*100f/s):l;} private boolean isCharging(){Intent i=batteryIntent();if(i==null)return false;int s=i.getIntExtra(BatteryManager.EXTRA_STATUS,-1);return s==BatteryManager.BATTERY_STATUS_CHARGING||s==BatteryManager.BATTERY_STATUS_FULL;}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL_ID,"REC Battery Monitor",NotificationManager.IMPORTANCE_LOW);c.setDescription("Pemantauan bateri WLAN");getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private Notification buildNotification(int b,boolean c){PendingIntent pi=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);String txt=Prefs.inSchedule(this)?((b>=0?b+"%":"-")+(c?" • sedang dicas":" • pemantauan aktif")):"Di luar waktu pemantauan";Notification.Builder n=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL_ID):new Notification.Builder(this);return n.setContentTitle("REC Battery Monitor").setContentText(txt).setSmallIcon(android.R.drawable.ic_lock_idle_charging).setContentIntent(pi).setOngoing(true).build();} private void updateNotification(int b,boolean c){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1001,buildNotification(b,c));}
 @Override public void onDestroy(){running=false;if(worker!=null)worker.interrupt();if(commandWorker!=null)commandWorker.interrupt();super.onDestroy();} @Override public IBinder onBind(Intent i){return null;}
}
