package com.recgombak.batterymonitor;
import android.app.*;import android.content.*;import android.os.*;import org.json.JSONObject;import java.net.*;import java.nio.charset.StandardCharsets;
public class ConfigAckService extends Service{
 private static final String CH="rec_config_ack";private volatile boolean running;private Thread thread;
 @Override public void onCreate(){super.onCreate();if(!"monitor".equals(Prefs.getRole(this))){stopSelf();return;}createChannel();startForeground(4200,note("Menunggu pengesahan tetapan tablet"));running=true;thread=new Thread(this::listen,"REC-Config-ACK");thread.start();}
 private void listen(){try(DatagramSocket s=new DatagramSocket(null)){s.setReuseAddress(true);s.bind(new InetSocketAddress(BatteryBroadcastService.PORT+3));s.setSoTimeout(3000);byte[] b=new byte[1024];while(running){try{DatagramPacket p=new DatagramPacket(b,b.length);s.receive(p);JSONObject o=new JSONObject(new String(p.getData(),p.getOffset(),p.getLength(),StandardCharsets.UTF_8));if(!"REC_BATTERY_ACK_1".equals(o.optString("app")))continue;String id=o.optString("id","unknown"),name=o.optString("name","Tablet");int low=o.optInt("low",-1),full=o.optInt("full",-1);long t=o.optLong("time",System.currentTimeMillis());Prefs.sp(this).edit().putInt("ack_low_"+id,low).putInt("ack_full_"+id,full).putLong("ack_time_"+id,t).putString("ack_name_"+id,name).putString("ack_ids",addId(Prefs.sp(this).getString("ack_ids",""),id)).apply();sendBroadcast(new Intent("com.recgombak.batterymonitor.ACK_UPDATED"));String x="✓ "+name+" terima arahan • LOW "+low+"% • FULL "+full+"%";((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(4300+Math.abs(id.hashCode()%500),note(x));}catch(SocketTimeoutException ignored){}catch(Exception ignored){}}}catch(Exception ignored){}}
 private String addId(String csv,String id){java.util.LinkedHashSet<String>s=new java.util.LinkedHashSet<>();if(csv!=null&&!csv.isEmpty())for(String x:csv.split(","))if(!x.isEmpty())s.add(x);s.add(id);return android.text.TextUtils.join(",",s);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel(CH,"Pengesahan Arahan Tablet",NotificationManager.IMPORTANCE_HIGH));}
 private Notification note(String x){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CH):new Notification.Builder(this);return b.setContentTitle("REC Battery Monitor").setContentText(x).setStyle(new Notification.BigTextStyle().bigText(x)).setSmallIcon(android.R.drawable.checkbox_on_background).setOngoing(false).build();}
 @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;}@Override public void onDestroy(){running=false;if(thread!=null)thread.interrupt();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
