package com.recgombak.batterymonitor;

import android.app.*;import android.content.*;import android.media.*;import android.os.*;import android.speech.tts.TextToSpeech;import org.json.JSONObject;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.Locale;

public class LowBatteryVoiceService extends Service{
 private static final String CHANNEL="rec_battery_voice";private BroadcastReceiver receiver;private TextToSpeech tts;private boolean ready=false,running=false;private Thread configThread;private PowerManager.WakeLock repeatWake;private final Handler h=new Handler(Looper.getMainLooper());private final Runnable repeatCheck=new Runnable(){public void run(){checkBattery();scheduleRepeat();}};

 @Override public void onCreate(){super.onCreate();createChannel();startForeground(4101,note("Memantau bateri tablet"));if(!"tablet".equals(Prefs.getRole(this))){stopSelf();return;}tts=new TextToSpeech(getApplicationContext(),s->{if(s==TextToSpeech.SUCCESS&&tts!=null){ready=true;try{tts.setLanguage(Locale.US);tts.setSpeechRate(.92f);tts.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build());}catch(Exception ignored){}checkBattery();}});receiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){checkBattery();scheduleRepeat();}};IntentFilter f=new IntentFilter(Intent.ACTION_BATTERY_CHANGED);f.addAction(Intent.ACTION_POWER_CONNECTED);f.addAction(Intent.ACTION_POWER_DISCONNECTED);f.addAction(Intent.ACTION_SCREEN_OFF);f.addAction(Intent.ACTION_SCREEN_ON);try{registerReceiver(receiver,f);}catch(Exception ignored){}running=true;configThread=new Thread(this::listenConfig,"REC-Voice-Config");configThread.start();}
 private void listenConfig(){try(DatagramSocket s=new DatagramSocket(null)){s.setReuseAddress(true);s.setBroadcast(true);s.bind(new InetSocketAddress(BatteryBroadcastService.PORT+2));s.setSoTimeout(3000);byte[] b=new byte[1024];while(running){try{DatagramPacket p=new DatagramPacket(b,b.length);s.receive(p);JSONObject o=new JSONObject(new String(p.getData(),p.getOffset(),p.getLength(),StandardCharsets.UTF_8));if(!"REC_BATTERY_VOICE_1".equals(o.optString("app")))continue;int low=limit(o.optInt("low",65)),full=limit(o.optInt("full",95));boolean fullEnabled=o.has("fullEnabled")?o.optBoolean("fullEnabled",true):Prefs.localChargeAlarmEnabled(this);Prefs.sp(this).edit().putInt("voice_low_threshold",low).putBoolean("voice_low_repeat",o.optBoolean("lowRepeat",false)).putInt("voice_low_repeat_min",limitMin(o.optInt("lowMin",3))).putInt("voice_full_threshold",full).putBoolean("voice_full_enabled",fullEnabled).putBoolean("voice_full_repeat",o.optBoolean("fullRepeat",false)).putInt("voice_full_repeat_min",limitMin(o.optInt("fullMin",3))).putLong("voice_last_low",0).putLong("voice_last_full",0).putLong("voice_config_received",System.currentTimeMillis()).apply();showConfigReceived(low,full,fullEnabled);sendAck(p.getAddress(),low,full,fullEnabled);checkBattery();scheduleRepeat();}catch(SocketTimeoutException ignored){}catch(Exception ignored){}}}catch(Exception ignored){}}
 private void sendAck(InetAddress monitor,int low,int full,boolean fullEnabled){try(DatagramSocket s=new DatagramSocket()){JSONObject o=new JSONObject();o.put("app","REC_BATTERY_ACK_1");o.put("id",Prefs.getId(this));o.put("name",Prefs.getName(this));o.put("low",low);o.put("full",full);o.put("fullEnabled",fullEnabled);o.put("time",System.currentTimeMillis());byte[] d=o.toString().getBytes(StandardCharsets.UTF_8);s.send(new DatagramPacket(d,d.length,monitor,BatteryBroadcastService.PORT+3));}catch(Exception ignored){}}
 private void showConfigReceived(int low,int full,boolean fullEnabled){String x="Tetapan diterima • LOW "+low+"% • FULL "+full+"%"+(fullEnabled?"":" (Monitor sahaja)");try{((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(4104,note(x));}catch(Exception ignored){}}
 private int limit(int v){return Math.max(1,Math.min(100,v));}private int limitMin(int v){return v==1||v==3||v==5||v==10?v:3;}
 private void checkBattery(){Intent i=registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));if(i==null)return;int l=i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),s=i.getIntExtra(BatteryManager.EXTRA_SCALE,100),pct=s>0?Math.round(l*100f/s):l,st=i.getIntExtra(BatteryManager.EXTRA_STATUS,-1);boolean charging=st==BatteryManager.BATTERY_STATUS_CHARGING||st==BatteryManager.BATTERY_STATUS_FULL;int low=Prefs.sp(this).getInt("voice_low_threshold",65),full=Prefs.sp(this).getInt("voice_full_threshold",95);boolean lowRepeat=Prefs.sp(this).getBoolean("voice_low_repeat",false),fullRepeat=Prefs.sp(this).getBoolean("voice_full_repeat",false),fullEnabled=Prefs.sp(this).getBoolean("voice_full_enabled",true);long lowMs=Prefs.sp(this).getInt("voice_low_repeat_min",3)*60000L,fullMs=Prefs.sp(this).getInt("voice_full_repeat_min",3)*60000L,now=System.currentTimeMillis();long lastLow=Prefs.sp(this).getLong("voice_last_low",0),lastFull=Prefs.sp(this).getLong("voice_last_full",0);if(charging||pct>low)Prefs.sp(this).edit().putLong("voice_last_low",0).apply();else if(pct>=0&&pct<=low&&(lastLow==0||(lowRepeat&&now-lastLow>=lowMs))){wakeScreen();speak(Prefs.getName(this)+", low battery. Please charge.");Prefs.sp(this).edit().putLong("voice_last_low",now).apply();notifyAlert(4102,Prefs.getName(this)+" • Low battery "+pct+"% — please charge");}if(!fullEnabled||!charging||pct<full)Prefs.sp(this).edit().putLong("voice_last_full",0).apply();else if(pct>=full&&(lastFull==0||(fullRepeat&&now-lastFull>=fullMs))){wakeScreen();speak(Prefs.getName(this)+", battery full. Please unplug the charger.");Prefs.sp(this).edit().putLong("voice_last_full",now).apply();notifyAlert(4103,Prefs.getName(this)+" • Battery "+pct+"% — unplug charger");}}
 private void scheduleRepeat(){h.removeCallbacks(repeatCheck);Intent i=registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));if(i==null){releaseRepeatWake();return;}int l=i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),s=i.getIntExtra(BatteryManager.EXTRA_SCALE,100),pct=s>0?Math.round(l*100f/s):l,st=i.getIntExtra(BatteryManager.EXTRA_STATUS,-1);boolean charging=st==BatteryManager.BATTERY_STATUS_CHARGING||st==BatteryManager.BATTERY_STATUS_FULL;int low=Prefs.sp(this).getInt("voice_low_threshold",65),full=Prefs.sp(this).getInt("voice_full_threshold",95);boolean lr=Prefs.sp(this).getBoolean("voice_low_repeat",false)&&!charging&&pct>=0&&pct<=low,fr=Prefs.sp(this).getBoolean("voice_full_enabled",true)&&Prefs.sp(this).getBoolean("voice_full_repeat",false)&&charging&&pct>=full;if(!lr&&!fr){releaseRepeatWake();return;}acquireRepeatWake();long delay=Long.MAX_VALUE;if(lr)delay=Math.min(delay,Prefs.sp(this).getInt("voice_low_repeat_min",3)*60000L);if(fr)delay=Math.min(delay,Prefs.sp(this).getInt("voice_full_repeat_min",3)*60000L);h.postDelayed(repeatCheck,Math.max(60000L,delay));}
 private void acquireRepeatWake(){try{if(repeatWake==null){PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);repeatWake=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"REC:ActiveBatteryRepeat");repeatWake.setReferenceCounted(false);}if(!repeatWake.isHeld())repeatWake.acquire();}catch(Exception ignored){}}
 private void releaseRepeatWake(){try{if(repeatWake!=null&&repeatWake.isHeld())repeatWake.release();}catch(Exception ignored){}}
 private void wakeScreen(){try{PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);PowerManager.WakeLock w=pm.newWakeLock(PowerManager.SCREEN_BRIGHT_WAKE_LOCK|PowerManager.ACQUIRE_CAUSES_WAKEUP,"REC:BatteryAlertScreen");w.acquire(12000);}catch(Exception ignored){}}
 private void speak(String x){if(!ready||tts==null)return;try{AudioManager a=(AudioManager)getSystemService(AUDIO_SERVICE);a.setStreamVolume(AudioManager.STREAM_ALARM,a.getStreamMaxVolume(AudioManager.STREAM_ALARM),0);tts.speak(x,TextToSpeech.QUEUE_FLUSH,null,"battery_voice");}catch(Exception ignored){}}
 private void notifyAlert(int id,String x){try{((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(id,note(x));}catch(Exception ignored){}}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel(CHANNEL,"Tablet Battery Voice",NotificationManager.IMPORTANCE_HIGH));}
 private Notification note(String x){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);return b.setContentTitle("REC Battery Monitor").setContentText(x).setStyle(new Notification.BigTextStyle().bigText(x)).setSmallIcon(android.R.drawable.ic_lock_idle_low_battery).setOngoing(true).build();}
 @Override public int onStartCommand(Intent i,int f,int id){checkBattery();scheduleRepeat();return START_STICKY;}@Override public void onDestroy(){running=false;h.removeCallbacks(repeatCheck);releaseRepeatWake();if(configThread!=null)configThread.interrupt();try{if(receiver!=null)unregisterReceiver(receiver);}catch(Exception ignored){}try{if(tts!=null){tts.stop();tts.shutdown();}}catch(Exception ignored){}super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
