package com.recgombak.batterymonitor;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.media.*;import android.net.Uri;import android.net.wifi.WifiManager;import android.os.*;import android.provider.Settings;import android.view.Gravity;import android.widget.*;import org.json.JSONObject;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity{
 private final Handler ui=new Handler(Looper.getMainLooper());private final Map<String,DeviceInfo> devices=Collections.synchronizedMap(new HashMap<>());private final Set<String>alerted=new HashSet<>();private LinearLayout root,list;private TextView subtitle,selfStatus;private volatile boolean listening;private DatagramSocket socket;private WifiManager.MulticastLock lock;private boolean weakOnly=false;
 @Override protected void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},44);if(Prefs.getRole(this).isEmpty())chooseRole();else launch();}
 private void chooseRole(){new AlertDialog.Builder(this).setTitle("Pilih mod peranti").setMessage("MONITOR untuk telefon cikgu. TABLET untuk tablet murid.").setCancelable(false).setPositiveButton("MONITOR",(d,w)->{Prefs.setRole(this,"monitor");launch();}).setNegativeButton("TABLET",(d,w)->{Prefs.setRole(this,"tablet");launch();}).show();}
 private void launch(){buildUi();if(Prefs.isEnabled(this))startBatteryService();if("monitor".equals(Prefs.getRole(this)))startListener();ui.post(refresh);}
 private void buildUi(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(24));root.setBackgroundColor(Color.rgb(247,248,250));s.addView(root);root.addView(tv("REC Battery Monitor",27,Color.rgb(15,23,42),true));root.addView(tv("Mod "+Prefs.getRole(this).toUpperCase(),13,Color.DKGRAY,true));if("monitor".equals(Prefs.getRole(this)))buildMonitor();else buildTablet();TextView foot=tv("Develop by cigunofal",12,Color.GRAY,true);foot.setGravity(Gravity.CENTER);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,-2);fp.setMargins(0,dp(24),0,dp(8));foot.setLayoutParams(fp);root.addView(foot);setContentView(s);}
 private void buildTablet(){LinearLayout c=card();c.addView(tv("TABLET INI",12,Color.GRAY,true));TextView name=tv(Prefs.getName(this),24,Color.rgb(15,23,42),true);c.addView(name);Button rename=button("Tukar nama");rename.setOnClickListener(v->rename(name));c.addView(rename);selfStatus=tv("Pemantauan aktif",17,Color.rgb(22,120,60),true);c.addView(selfStatus);root.addView(c);Button bg=button("Benarkan berjalan di background");bg.setOnClickListener(v->openBatterySettings());root.addView(bg);Button mode=button("Tukar ke Mod Monitor");mode.setOnClickListener(v->{Prefs.setRole(this,"monitor");recreate();});root.addView(mode);root.addView(tv("Tablet ini hanya menghantar status bateri. Ia tidak memaparkan bateri tablet lain.",13,Color.GRAY,false));}
 private void buildMonitor(){subtitle=tv("Mengesan tablet dalam WLAN…",14,Color.DKGRAY,false);root.addView(subtitle);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button ref=button("↻ Refresh Semua");ref.setOnClickListener(v->sendCommand("ALL","refresh",0));actions.addView(ref,new LinearLayout.LayoutParams(0,-2,1));Button weak=button("Tablet Lemah");weak.setOnClickListener(v->{weakOnly=!weakOnly;weak.setText(weakOnly?"Tunjuk Semua":"Tablet Lemah");render();});actions.addView(weak,new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);Button settings=button("⚙ Tetapan Monitor");settings.setOnClickListener(v->settingsDialog());root.addView(settings);root.addView(tv("TABLET DALAM WLAN",13,Color.DKGRAY,true));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);Button mode=button("Tukar ke Mod Tablet");mode.setOnClickListener(v->{Prefs.setRole(this,"tablet");recreate();});root.addView(mode);}
 private void settingsDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(24),0,dp(24),0);EditText threshold=new EditText(this);threshold.setInputType(2);threshold.setHint("Paras amaran %");threshold.setText(String.valueOf(Prefs.getThreshold(this)));box.addView(label("Penggera berbunyi pada / bawah (%)"));box.addView(threshold);EditText interval=new EditText(this);interval.setInputType(2);interval.setText(String.valueOf(Prefs.getInterval(this)));box.addView(label("Kemas kini setiap (saat, minimum 5)"));box.addView(interval);CheckBox schedule=new CheckBox(this);schedule.setText("Gunakan jadual pemantauan");schedule.setChecked(Prefs.scheduleOn(this));box.addView(schedule);Button start=button("Mula: "+timeText(Prefs.getStartMin(this)));Button end=button("Tamat: "+timeText(Prefs.getEndMin(this)));final int[] times={Prefs.getStartMin(this),Prefs.getEndMin(this)};start.setOnClickListener(v->pickTime(times,0,start,"Mula: "));end.setOnClickListener(v->pickTime(times,1,end,"Tamat: "));box.addView(start);box.addView(end);new AlertDialog.Builder(this).setTitle("Tetapan Monitor").setView(box).setPositiveButton("Simpan",(d,w)->{try{Prefs.setThreshold(this,Integer.parseInt(threshold.getText().toString()));}catch(Exception ignored){}try{Prefs.setInterval(this,Integer.parseInt(interval.getText().toString()));}catch(Exception ignored){}Prefs.setScheduleOn(this,schedule.isChecked());Prefs.setSchedule(this,times[0],times[1]);alerted.clear();}).setNegativeButton("Batal",null).show();}
 private TextView label(String s){return tv(s,13,Color.DKGRAY,true);}private void pickTime(int[] a,int idx,Button b,String pre){int m=a[idx];new TimePickerDialog(this,(v,h,min)->{a[idx]=h*60+min;b.setText(pre+timeText(a[idx]));},m/60,m%60,false).show();}private String timeText(int m){int h=m/60,min=m%60;String ap=h>=12?"PM":"AM";int hh=h%12;if(hh==0)hh=12;return String.format(Locale.US,"%d:%02d %s",hh,min,ap);}
 private void rename(TextView v){EditText i=new EditText(this);i.setText(Prefs.getName(this));new AlertDialog.Builder(this).setTitle("Nama tablet").setView(i).setPositiveButton("Simpan",(d,w)->{String n=i.getText().toString().trim();if(!n.isEmpty()){Prefs.setName(this,n);v.setText(n);}}).setNegativeButton("Batal",null).show();}
 private void openBatterySettings(){try{Intent i=new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, Uri.parse("package:"+getPackageName()));startActivity(i);}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}}
 private void startBatteryService(){Intent i=new Intent(this,BatteryBroadcastService.class);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception ignored){}}
 private void startListener(){if(listening)return;listening=true;try{WifiManager w=(WifiManager)getApplicationContext().getSystemService(Context.WIFI_SERVICE);lock=w.createMulticastLock("recBatteryLock");lock.setReferenceCounted(false);lock.acquire();}catch(Exception ignored){}new Thread(this::listen).start();}
 private void listen(){try{socket=new DatagramSocket(null);socket.setReuseAddress(true);socket.setBroadcast(true);socket.bind(new InetSocketAddress(BatteryBroadcastService.PORT));socket.setSoTimeout(3000);byte[] buf=new byte[2048];while(listening){try{DatagramPacket p=new DatagramPacket(buf,buf.length);socket.receive(p);JSONObject o=new JSONObject(new String(p.getData(),p.getOffset(),p.getLength(),StandardCharsets.UTF_8));String app=o.optString("app");if(!"REC_BATTERY_V2".equals(app)&&!"REC_BATTERY_V1".equals(app))continue;String id=o.optString("id");if(id.isEmpty()||id.equals(Prefs.getId(this)))continue;DeviceInfo d=devices.get(id);if(d==null)d=new DeviceInfo();d.id=id;d.name=o.optString("name","Tablet");d.model=o.optString("model","Android");d.battery=o.optInt("battery",-1);d.charging=o.optBoolean("charging",false);d.timerEnd=o.optLong("timerEnd",0);d.lastSeen=System.currentTimeMillis();d.ip=p.getAddress().getHostAddress();devices.put(id,d);}catch(SocketTimeoutException ignored){}catch(Exception ignored){}}}catch(Exception ignored){}}
 private void sendCommand(String target,String cmd,int minutes){new Thread(()->{try{JSONObject o=new JSONObject();o.put("app","REC_BATTERY_V2");o.put("target",target);o.put("cmd",cmd);if(minutes>0)o.put("minutes",minutes);byte[] d=o.toString().getBytes(StandardCharsets.UTF_8);try(DatagramSocket s=new DatagramSocket()){s.setBroadcast(true);s.send(new DatagramPacket(d,d.length,InetAddress.getByName("255.255.255.255"),BatteryBroadcastService.PORT+1));}}catch(Exception ignored){}}).start();}
 private final Runnable refresh=new Runnable(){public void run(){if("monitor".equals(Prefs.getRole(MainActivity.this)))render();else renderSelf();ui.postDelayed(this,1000);}};
 private void renderSelf(){if(selfStatus==null)return;long end=Prefs.getTimerEnd(this),left=end-System.currentTimeMillis();if(end>0&&left<=0){selfStatus.setText("MASA TAMAT");selfStatus.setTextColor(Color.RED);}else if(left>0)selfStatus.setText("Pemantauan aktif • Timer "+formatDuration(left));else selfStatus.setText(Prefs.inSchedule(this)?"Pemantauan aktif":"Di luar waktu pemantauan");}
 private void render(){if(list==null)return;List<DeviceInfo> data; synchronized(devices){data=new ArrayList<>(devices.values());}data.sort(Comparator.comparingInt(a->a.battery<0?101:a.battery));list.removeAllViews();long now=System.currentTimeMillis();int threshold=Prefs.getThreshold(this),online=0;for(DeviceInfo d:data)if(now-d.lastSeen<=Math.max(60,Prefs.getInterval(this)*4)*1000L)online++;subtitle.setText(online+" online • "+data.size()+" pernah dikesan • amaran ≤ "+threshold+"%");for(DeviceInfo d:data){boolean on=now-d.lastSeen<=Math.max(60,Prefs.getInterval(this)*4)*1000L;if(weakOnly&&on&&d.battery>threshold)continue;if(on&&d.battery>=0&&d.battery<=threshold&&!d.charging){if(!alerted.contains(d.id)){alerted.add(d.id);alarm();}}else if(d.battery>threshold||d.charging)alerted.remove(d.id);LinearLayout c=card();LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.VERTICAL);left.addView(tv(d.name,20,Color.rgb(15,23,42),true));left.addView(tv(d.model+" • "+age(now-d.lastSeen),12,Color.GRAY,false));row.addView(left,new LinearLayout.LayoutParams(0,-2,1));int col=!on?Color.GRAY:d.battery<=20?Color.rgb(220,38,38):d.battery<=40?Color.rgb(217,119,6):Color.rgb(22,163,74);TextView batt=tv((d.battery<0?"--":d.battery)+"%",30,col,true);row.addView(batt);c.addView(row);String st=!on?"OFFLINE • bacaan terakhir":(d.charging?"⚡ SEDANG DICAS":"● ONLINE");if(d.timerEnd>now)st+=" • ⏱ "+formatDuration(d.timerEnd-now);else if(d.timerEnd>0)st+=" • MASA TAMAT";c.addView(tv(st,12,on?Color.DKGRAY:Color.GRAY,true));LinearLayout buttons=new LinearLayout(this);Button timer=button("Timer");timer.setOnClickListener(v->timerDialog(d));buttons.addView(timer,new LinearLayout.LayoutParams(0,-2,1));Button refreshOne=button("Refresh");refreshOne.setOnClickListener(v->sendCommand(d.id,"refresh",0));buttons.addView(refreshOne,new LinearLayout.LayoutParams(0,-2,1));c.addView(buttons);list.addView(c);}if(list.getChildCount()==0){LinearLayout c=card();c.addView(tv(weakOnly?"Tiada tablet lemah":"Belum ada tablet dikesan",18,Color.DKGRAY,true));list.addView(c);}}
 private void timerDialog(DeviceInfo d){EditText e=new EditText(this);e.setInputType(2);e.setHint("Contoh: 30");new AlertDialog.Builder(this).setTitle("Timer • "+d.name).setMessage("Tetapkan minit penggunaan. Apabila tamat, app tablet akan paparkan MASA TAMAT.").setView(e).setPositiveButton("Mula",(x,w)->{try{sendCommand(d.id,"timer",Integer.parseInt(e.getText().toString()));}catch(Exception ignored){}}).setNeutralButton("Padam Timer",(x,w)->sendCommand(d.id,"clearTimer",0)).setNegativeButton("Batal",null).show();}
 private void alarm(){try{AudioManager am=(AudioManager)getSystemService(AUDIO_SERVICE);int max=am.getStreamMaxVolume(AudioManager.STREAM_ALARM);am.setStreamVolume(AudioManager.STREAM_ALARM,max,0);ToneGenerator tg=new ToneGenerator(AudioManager.STREAM_ALARM,100);tg.startTone(ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD,12000);ui.postDelayed(tg::release,12500);}catch(Exception ignored){}}
 private String formatDuration(long ms){long sec=Math.max(0,ms/1000),m=sec/60,s=sec%60;return String.format(Locale.US,"%02d:%02d",m,s);}private String age(long ms){long s=Math.max(0,ms/1000);return s<5?"sekarang":s<60?s+"s lalu":(s/60)+"m lalu";}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));android.graphics.drawable.GradientDrawable bg=new android.graphics.drawable.GradientDrawable();bg.setColor(Color.WHITE);bg.setCornerRadius(dp(16));bg.setStroke(dp(1),Color.LTGRAY);c.setBackground(bg);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(8),0,dp(6));c.setLayoutParams(lp);return c;}private TextView tv(String t,int sp,int col,boolean bold){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(col);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private Button button(String t){Button b=new Button(this);b.setText(t);b.setAllCaps(false);return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 @Override protected void onDestroy(){listening=false;ui.removeCallbacks(refresh);if(socket!=null)socket.close();if(lock!=null&&lock.isHeld())lock.release();super.onDestroy();}
}
